create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  order_number text unique,
  email text not null,
  contact text,
  comment text,
  total_rub numeric not null default 0,
  status text not null default 'new'
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price_rub numeric not null default 0,
  line_total_rub numeric not null default 0
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Service role manages orders" on public.orders;
create policy "Service role manages orders"
on public.orders
for all
to service_role
using (true)
with check (true);

drop policy if exists "Service role manages order items" on public.order_items;
create policy "Service role manages order items"
on public.order_items
for all
to service_role
using (true)
with check (true);
